// This disables a TypeScript linting rule that can sometimes flag class-validator decorators.
// Keep it if ESLint complains about class-validator usage.

import {
  IsNotEmpty,
  IsString,
  IsOptional,
  IsBoolean,
  IsInt,
  Min,
} from 'class-validator';
// Import validation decorators from "class-validator".
// These are used by NestJS pipes to validate incoming request bodies.

// DTO = Data Transfer Object
// It defines what data structure and validation rules are expected from client requests.

export class CreateTodoDto {
  // 🆔 ID field (optional)
  // Usually auto-generated by the database, but you can include it if:
  // - You want to manually set IDs (e.g., during testing or data import)
  // - You’re using a non-auto-increment primary key
  @IsInt() // Ensures the value is an integer
  @Min(1) // Ensures ID is at least 1
  @IsOptional() // Optional because the database usually generates it automatically
  id?: number;

  // 📝 Title field — required and must be a string
  // Example: { "title": "Buy milk" }
  @IsString() // Ensures the value is a string
  @IsNotEmpty() // Ensures it's not empty or whitespace
  title: string;

  // ✅ Completed field — optional boolean
  // If omitted, defaults to false in the entity
  @IsBoolean() // Ensures the value is true or false
  @IsOptional() // Allows this field to be missing
  completed?: boolean; // Optional in both TS and validation
}
